export {
  MASTERY_CONFIG,
  accuracyScore,
  applyAttempt,
  computeMastery,
  confidenceFromSamples,
  derivedTableMastery,
  emptyFactRecord,
  isHighConfidence,
  isMasteredFact,
  isStrongFact,
  recencyScore,
  speedScore,
} from './mastery'

export {
  awardGameXp,
  bucketFacts,
  classifyFact,
  createEmptyPlayerProgress,
  createEmptyProfile,
  createEmptySkillProgress,
  ensureFact,
  recordBest,
  touchDailyStreak,
  dayKey,
  selectNextFact,
  type SelectionResult,
} from './selection'

export {
  applyPlacementResult,
  applyStartLevelInference,
  buildPlacementSequence,
  completePlacement,
  inferStartLevel,
  nextProbe,
  placementResult,
  recordProbe,
  seedPlacementAttempt,
  startPlacement,
  type PlacementItem,
  type PlacementState,
} from './placement'

export {
  applyAttemptToEvidence,
  countedAttempts,
  countedFlags,
  detectComebacks,
  emptyFactEvidence,
  evaluateAdvancement,
  evaluateMixedLevel,
  evaluateTableLevel,
  factMarks,
  factStatus,
  isLikelyCorrect,
  levelAllowance,
  levelMarksTotal,
  rebuildEvidence,
  type AdvancementInput,
} from './advancement'
